name = "nowplaying-hono"
main = "src/index.ts"
compatibility_date = "2023-03-21"

kv_namespaces = [
{ binding = "CACHE_TOKEN", id = "6dab2ca4f73040d3bc074aeba100dc63" },
{ binding = "TRACK_CACHE", id = "5bd461ba4e404db0ad25635b113b5ad1" }
]

# The necessary secrets are:
# - SPOTIFY_CLIENT_ID
# - SPOTIFY_CLIENT_SECRET
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
